nb1 = input("Enter the first number : ")
nb2 = input("Enter the second number : ")
print("\n")
print("The user type " + nb1)
print("The user type " + nb2 + "\n")
som = int(nb1) + int(nb2)
dif = int(nb1) - int (nb2)
print("Somme : " + str(lsom))
print("Difference : " + str(dif))
